import base64
import os

# A simple 16x16 icon (blue square-ish)
ICON_BASE64 = """
AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAD/
/////////wAAAAAAAAAAAAAAAAMCAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAIC
AgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgIAAAAAAAAA
AAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgIC
AgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAA
AAAAAAAAAAICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgIC
AgIAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAA
AAICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgIAAAAA
AAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgIC
AgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgICAgICAgICAgICAgIAAAAAAAAAAAAA
AAAAAAAAAAAAAAICAgICAgICAgICAgICAgIAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////AAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
"""

output_path = "/Users/m2pro/HeySeen/heyseen/server/static/favicon.ico"

try:
    with open(output_path, "wb") as f:
        f.write(base64.b64decode(ICON_BASE64.strip()))
    print(f"Successfully created favicon at {output_path}")
except Exception as e:
    print(f"Error creating favicon: {e}")
